# -*- coding: utf-8 -*-
"""350_Arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1owKq90Uc4U1VAeahl8S731pTGFwAPk7u
"""

#1 : Reverse Array or String  https://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/
# O(n) time, O(1) space

def reverse(array):
  start = 0
  end = len(array) - 1
  while start < end:
    array[start], array[end] = array[end], array[start]
    start += 1
    end -= 1
  return array

reverse([1,2,3,4,5])

#one liner
def reverse2(array):
  print(array[::-1])

reverse2([1,3,3,4,5])

#2 Maximum and minimum of an array using minimum number of comparisons : https://www.geeksforgeeks.org/maximum-and-minimum-in-an-array/
# time - O(n), space - O(1)

class pair:
    def __init__(self):
        self.min = 0
        self.max = 0
 
def getMinMax(arr: list, n: int) -> pair:
    minmax = pair()
 
    # If there is only one element then return it as min and max both
    if n == 1:
        minmax.max = arr[0]
        minmax.min = arr[0]
        return minmax
 
    # If there are more than one elements, then initialize min
    # and max
    if arr[0] > arr[1]:
        minmax.max = arr[0]
        minmax.min = arr[1]
    else:
        minmax.max = arr[1]
        minmax.min = arr[0]
 
    for i in range(2, n):
        if arr[i] > minmax.max:
            minmax.max = arr[i]
        elif arr[i] < minmax.min:
            minmax.min = arr[i]
 
    return minmax
 
# Driver Code
if __name__ == "__main__":
    arr = [1000, 11, 445, 1, 330, 3000]
    arr_size = 6
    minmax = getMinMax(arr, arr_size)
    print("Minimum element is", minmax.min)
    print("Maximum element is", minmax.max)


#direct
min(arr)
max(arr)



a = [1,2]
len(a)